#!/usr/bin/env python
import os
import argparse

def get_args():
    default_file=os.environ['HOME'] + '/Documents/contacts.txt'

    parser=argparse.ArgumentParser(description="CONTACT Management")
    parser.add_argument("--edit", "-e",  action="store_true")
    parser.add_argument("--title", "-t", action="store_true")
    parser.add_argument("--file", "-f",  metavar='<file>', default=default_file)
    parser.add_argument("text", nargs="?", metavar="<text>")
    return(parser.parse_args())

def main():
    args = get_args()
    if args.edit:
        return(os.system("vi {}".format(args.file)))

    if not args.text and not args.title:
        return(os.system("cat {}".format(args.file)))

    just_titles = not args.text and args.title

    match = False
    with open(args.file, 'r') as f:
        lines = [line[:-1] for line in f.readlines()]
        for i in range(len(lines)):
           if lines[i][0:1] not in ['', ' ', '\t']: # check for section title (nonblank line w/o leading white space)
              section_start=i
              match = False

           if (not match) and (not just_titles): # print title and section...
               if lines[i].lower().find(args.text.lower()) != -1: # check for a match
                   print ("\n".join(lines[section_start:(section_start+1) if args.title else i+1]))
                   match = True # record the match
           
           elif ( just_titles and (section_start == i) ) or ( (not just_titles) and (not args.title) ): # print titles or matching sections
               print(lines[i])
main()
